Update CI/CD After second test

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -22,7 +22,7 @@ jobs:
         run: |
           echo "Checking required submission files..."
           test -f README.md || (echo "Missing README.md" && exit 1)
-          test -f docs/PROG_Database.sql || (echo "Missing PROG_Database.sql in /docs" && exit 1)
+          test -f docs/SQLQuery1.sql || (echo "Missing SQLQuery.sql in /docs" && exit 1)
           test -f docs/api-endpoint-plan.md || (echo "Missing api-endpoint-plan.md in /docs" && exit 1)
           echo "All core documentation files present."
 
